version: "3.7"

services:
  db:
    container_name: postgres-dev-db
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgrespw
    restart: unless-stopped
    ports:
      - "55000:5432"